import { evaluate, actualEvidence } from './readiness.mjs';
import { definitionHash } from './record-contracts.mjs';
import { legacyReviewModel } from './legacy-review.mjs';
import { legacyAdoptionModel } from './legacy-adoption.mjs';

export function briefing(view, { module, id } = {}) {
  const records = view.records, selected = records.filter(r => (!module || r.owner.id === module) && (!id || r.id === id || r.definition.change === id));
  const evaluations = selected.filter(r => ['CHG', 'WRK', 'REL'].includes(r.type)).map(r => evaluate(records, r.id, r.type === 'WRK' ? 'development' : r.type === 'REL' ? 'release' : 'requirements', view));
  const discovery = selected.filter(r => r.type === 'CHG').map(r => evaluate(records, r.id, 'discovery', view));
  const modules = records.filter(r => r.type === 'MOD' && (!module || r.id === module)).map(r => {
    const cycles = records.filter(c => c.type === 'CHG' && (c.owner.id === r.id || c.definition.modules?.includes(r.id))).map(c => ({ id: c.id, title: c.title, execution: c.execution?.status ?? 'planned', readiness: evaluate(records, c.id, 'requirements', view).readiness }));
    const releases = records.filter(rel => rel.type === 'REL' && rel.owner.id === r.id && rel.execution?.status === 'completed' && actualEvidence(records, rel, 'integration')).map(rel => ({ id: rel.id, title: rel.title, baseline: rel.definition.baseline ?? null, environment: rel.definition.environment, historical: true }));
    return { id: r.id, title: r.title, purpose: r.definition.purpose ?? null, operating_releases: releases, cycles, state: releases.length ? 'operating' : cycles.length ? 'in_progress' : 'planned' };
  });
  const relevantIds = new Set(selected.map(r => r.id));
  const related = r => selected.includes(r) || r.definition.applies_to?.some(s => s === 'project' || relevantIds.has(s)) || r.relations.some(rel => relevantIds.has(rel.target));
  const questions = records.filter(r => related(r) && r.type === 'DRQ' && !['completed', 'cancelled'].includes(r.execution?.status)).sort((a, b) => Number(b.definition.blocking ?? true) - Number(a.definition.blocking ?? true) || (a.definition.priority ?? 99) - (b.definition.priority ?? 99) || String(a.definition.asked_at ?? '').localeCompare(String(b.definition.asked_at ?? '')) || (a.definition.sequence ?? 0) - (b.definition.sequence ?? 0)).map(r => ({ id: r.id, title: r.title, ...r.definition, status: r.definition.status ?? 'draft' }));
  const waiting = questions.filter(q => q.status === 'awaiting_decision');
  const first = waiting[0], recommended = first ? waiting.filter(q => q.asked_at === first.asked_at).sort((a,b) => (a.sequence ?? 0)-(b.sequence ?? 0)) : [];
  const pending_merges = records.filter(r => related(r) && ['MRG','MRC'].includes(r.type) && !['completed','cancelled'].includes(r.execution?.status)).map(r => ({id:r.id,type:r.type,title:r.title,...r.definition,execution:r.execution}));
  const decision_summary = { counts:Object.fromEntries(['draft','awaiting_decision','deferred'].map(s => [s,questions.filter(q => q.status === s).length])), waiting_groups:new Set(waiting.map(q => q.asked_at ?? q.id)).size, blocking:waiting.filter(q => q.blocking !== false).length };
  const counts = Object.fromEntries(['planned', 'in_progress', 'blocked', 'completed', 'cancelled'].map(status => [status, selected.filter(r => r.type === 'WRK' && (r.execution?.status ?? 'planned') === status).length]));
  const legacy_reviews = selected.filter(r=>r.type==='CHG'&&r.relations.some(e=>records.some(p=>p.id===e.target&&p.definition.kind==='reverse_engineering'))).map(r=>{const m=legacyReviewModel(records,r.id,{coverage:view.coverage});return {change:r.id,analysis:m.analysis,counts:m.counts,phases:m.phases,next_stage:m.next_stage,requirement_readiness:m.requirement_readiness,coverage_gaps:m.coverage_gaps};});
  const legacy_adoptions=legacy_reviews.flatMap(r=>(records.find(c=>c.id===r.change)?.definition.modules??[]).filter(m=>!module||m===module).map(m=>legacyAdoptionModel(records,r.change,m,{coverage:view.coverage})));
  return { schema_version: 2, scope: module ? { module } : id ? { id } : { project: true }, snapshot_token: view.snapshot_token, coverage: view.coverage, diagnostics: view.diagnostics, modules, discovery, legacy_reviews, legacy_adoptions, evaluations, work_counts: counts, open_items: records.filter(r => related(r) && r.type === 'OI' && !['completed', 'cancelled'].includes(r.execution?.status)).map(r => ({ id: r.id, title: r.title, applies_to: r.definition.applies_to ?? [] })), pending_merges, decision_summary, pending_decisions: questions, recommended_question: first ?? null, recommended_questions:recommended, next_actions: evaluations.flatMap(e => e.next_actions), definitions: selected.map(r => ({ id: r.id, definition_hash: definitionHash(r) })), note: '완료 수는 기록된 실행 상태이며 현재 준비도/증거 유효성과 별도로 표시한다. 운영 이력은 현재 재검토와 구분한다.' };
}
export function briefingText(model) {
  const adoptionText=(model.legacy_adoptions??[]).map(m=>`- ${m.module}/${m.change}: 문서 ${m.documentation.readiness}, 채택 ${m.adoption.status}, 실제 검증 ${m.runtime.status}; 소스 현행 재검사는 별도`).join('\n');
  const discovery = (model.discovery ?? []).map(e => `- ${e.scope.id}: ${e.readiness} (${e.validity})`).join('\n') + ((model.legacy_reviews??[]).length ? '\n\n## 레거시 정본 검토\n\n'+model.legacy_reviews.map(m=>`- ${m.change}: 현재 수용 ${m.counts.current}/${m.counts.total}, 재검토 ${m.counts.stale}, 미완료 ${m.counts.pending}; 요구 준비도 ${m.requirement_readiness}; 다음 ${m.next_stage===null?'일반 게이트 확인':m.phases[m.next_stage].title}`).join('\n') : '');
  const decisionTail = `${adoptionText?'\n## 레거시 문서 도입과 검증\n\n'+adoptionText+'\n':''}\n## 답변 대기 요약\n\n${model.decision_summary?.counts.awaiting_decision ?? 0}건 / ${model.decision_summary?.waiting_groups ?? 0}묶음; 초안 ${model.decision_summary?.counts.draft ?? 0}, 보류 ${model.decision_summary?.counts.deferred ?? 0}\n\n## 병합 재검토\n\n${(model.pending_merges ?? []).map(m => `- ${m.id}: ${m.title}`).join('\n') || '없음'}\n\n## 권장 질문 묶음\n\n${(model.recommended_questions ?? []).map(q => `- ${q.id}: ${q.question ?? q.title}\n  선택지: ${JSON.stringify(q.options ?? [])}; 권장: ${q.recommendation ?? '미기록'}`).join('\n') || '없음'}\n`;
  return `# 프로젝트 상태\n\n${model.note}\n\n${model.modules.map(m => `- ${m.id} ${m.title}: ${m.state}; 운영 릴리스 ${m.operating_releases.length}, 주기 ${m.cycles.length}`).join('\n')}\n\n## 선행 업무 분석\n\n${discovery || '분석 주기 없음'}\n\n## 현재 준비도\n\n${model.evaluations.map(e => `- ${e.scope.id}: ${e.readiness} (${e.validity})\n${e.blockers.map(b => `  - ${b.subject}: ${b.reason} [${b.code}]`).join('\n')}${e.unknowns.length ? `\n  - unknown: ${e.unknowns.map(x => x.code).join(', ')}` : ''}`).join('\n')}\n\n## 다음 작업\n\n${model.next_actions.map(a => `- ${a.subject ?? '범위'}: ${a.action}`).join('\n') || '차단 원인 없음. 해당 작업의 현재 입력과 실행 계획을 확인하세요.'}\n\n## 미응답 결정\n\n${model.pending_decisions.map(q => `- ${q.id}: ${q.question ?? q.title}`).join('\n') || '없음'}\n` + decisionTail;
}
