import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT=resolve(import.meta.dirname,"../..");
const HOOK=join(ROOT,".ai/tools/aidd_hook.mjs");
function run(args,input="",env={}){return spawnSync(process.execPath,[HOOK,...args],{cwd:ROOT,input,encoding:"utf8",env:{...process.env,...env}});}
function payload(tool_input,tool_name="apply_patch"){return JSON.stringify({tool_name,tool_input});}

test("self-test validates both providers",()=>{const result=run(["self-test"]);assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/passed/);});
test("only Codex enforces the approval gate",()=>{const codex=JSON.parse(readFileSync(join(ROOT,".codex/hooks.json"),"utf8")),contract=JSON.parse(readFileSync(join(ROOT,".ai/hooks/contract.json"),"utf8"));const sessionStart=JSON.stringify(codex.hooks.SessionStart),preTool=JSON.stringify(codex.hooks.PreToolUse),userPrompt=JSON.stringify(codex.hooks.UserPromptSubmit);assert.match(sessionStart,/hook-trust-status/);assert.match(sessionStart,/approval-status/);assert.match(preTool,/approval-gate/);assert.match(userPrompt,/acknowledge/);assert.deepEqual(contract.events.PreToolUse.provider_required_tokens.codex,["approval-gate"]);assert.doesNotMatch(JSON.stringify(contract.events),/claude.*approval-gate/);const sandbox=mkdtempSync(join(tmpdir(),"aidd-claude-approval-test-"));try{const result=run(["approval-gate","--platform","claude"],JSON.stringify({session_id:"claude-session",tool_name:"Write",tool_input:{path:"x"}}),{AIDD_HOOK_APPROVAL_DIR:join(sandbox,"approvals")});assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("tool work accepts a clear existing-approval meaning without exact wording",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-approval-test-")),env={AIDD_HOOK_APPROVAL_DIR:join(sandbox,"approvals")},session_id="approval-test-session";try{let result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.equal(result.status,0,result.stderr);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/정해진 문구를 그대로 쓸 필요는 없습니다/);result=run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt:"네, `AIDD 훅` 내용을 확인하고 승인했어요."}),env);assert.equal(result.status,0,result.stderr);result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);const reason=JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason;assert.match(reason,/두 선택지/);assert.match(reason,/1\).*2\)/);result=run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt:"이미 승인되어 있었음"}),env);assert.equal(result.status,0,result.stderr);result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("Windows Desktop new approval accepts a numbered choice and requires a natural restart confirmation",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-restart-test-")),env={AIDD_HOOK_APPROVAL_DIR:join(sandbox,"approvals"),CODEX_INTERNAL_ORIGINATOR_OVERRIDE:"Codex Desktop"},oldSession="approval-old-session",newSession="approval-new-session";try{let result=run(["acknowledge","--platform","codex"],JSON.stringify({session_id:oldSession,prompt:"훅을 검토한 다음 승인 완료했어"}),env);assert.equal(result.status,0,result.stderr);result=run(["acknowledge","--platform","codex"],JSON.stringify({session_id:oldSession,prompt:"2번"}),env);assert.equal(result.status,0,result.stderr);result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id:oldSession,tool_name:"apply_patch",tool_input:{patch:"*** Update File: project/src/a.js"}}),env);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/새 Codex 앱 창/);result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id:newSession,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/정해진 문구를 그대로 쓸 필요는 없습니다/);result=run(["acknowledge","--platform","codex"],JSON.stringify({session_id:newSession,prompt:"새 Codex 창을 열어 다시 시작했고 훅도 승인된 상태예요"}),env);assert.equal(result.status,0,result.stderr);result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id:newSession,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("Codex CLI new approval becomes effective without an app restart",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-cli-approval-test-")),env={AIDD_HOOK_APPROVAL_DIR:join(sandbox,"approvals"),CODEX_INTERNAL_ORIGINATOR_OVERRIDE:"Codex CLI",CODEX_WINDOWS_SANDBOX_PACKAGE_FAMILY:""},session_id="approval-cli-session";try{for(const prompt of ["AIDD 훅을 확인하고 승인했어요","현재 세션 시작 후 훅을 방금 새로 승인했어"])assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt}),env).status,0);const result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");const state=JSON.parse(readFileSync(join(env.AIDD_HOOK_APPROVAL_DIR,"hook-state.json"),"utf8"));assert.equal(state.restart_required,null);}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("ambiguous or negative approval replies remain blocked",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-approval-negative-test-")),env={AIDD_HOOK_APPROVAL_DIR:join(sandbox,"approvals")},session_id="approval-negative-session";try{for(const prompt of ["훅은 아직 검토 안 했어요","AIDD 훅을 검토했고 승인했습니다 라고 말하면 돼?"]){assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt}),env).status,0);const result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/직접 검토하고 승인했다는 뜻/);}assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt:"훅을 확인하고 승인했어"}),env).status,0);assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt:"이번 세션에서 승인했는지 잘 모르겠어"}),env).status,0);const result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git status --short"}}),env);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/두 선택지/);}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("stale sessions permit only hook maintenance and their observed close-out paths",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-stale-test-")),root=join(sandbox,"approvals"),env={AIDD_HOOK_APPROVAL_DIR:root},session_id="stale-session";try{for(const prompt of ["AIDD 훅을 검토했고 승인했습니다","이번 세션 전에 이미 승인되어 있었습니다"])assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt}),env).status,0);const post={session_id,tool_name:"apply_patch",tool_input:{patch:"*** Update File: project/src/owned.js\n@@"}};assert.equal(run(["post-check","--platform","codex"],JSON.stringify(post),env).status,0);const statePath=join(root,"hook-state.json"),state=JSON.parse(readFileSync(statePath,"utf8")),key=state.sessions[Object.keys(state.sessions)[0]].session_key;state.sessions[key].start_revision="old-revision";writeFileSync(statePath,`${JSON.stringify(state)}\n`,`utf8`);let result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"apply_patch",tool_input:{patch:"*** Update File: .ai/tools/aidd_hook.mjs\n@@"}}),env);assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git add project/src/owned.js"}}),env);assert.equal(result.stdout,"");result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name:"Bash",tool_input:{command:"git add project/src/other.js"}}),env);assert.match(JSON.parse(result.stdout).hookSpecificOutput.permissionDecisionReason,/일반 작업은 금지/);}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("stale sessions permit read-only web documentation tools",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-stale-web-test-")),root=join(sandbox,"approvals"),env={AIDD_HOOK_APPROVAL_DIR:root},session_id="stale-web-session";try{for(const prompt of ["훅을 검토하고 승인했어요","1번"])assert.equal(run(["acknowledge","--platform","codex"],JSON.stringify({session_id,prompt}),env).status,0);const statePath=join(root,"hook-state.json"),state=JSON.parse(readFileSync(statePath,"utf8")),key=Object.keys(state.sessions)[0];state.sessions[key].start_revision="old-revision";writeFileSync(statePath,`${JSON.stringify(state)}\n`,`utf8`);for(const tool_name of ["web.run","web__run","webrun"]){const result=run(["approval-gate","--platform","codex"],JSON.stringify({session_id,tool_name,tool_input:{search_query:[{q:"official docs"}]}}),env);assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,"");}}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("malformed input fails closed",()=>{const result=run(["protect","--platform","codex","--kind","file"],"{");assert.equal(result.status,0);assert.equal(JSON.parse(result.stdout).hookSpecificOutput.permissionDecision,"deny");});
test("generated document write is denied",()=>{const result=run(["protect","--platform","codex","--kind","file"],payload({path:"project/docs/generated/index.md"}));assert.equal(JSON.parse(result.stdout).hookSpecificOutput.permissionDecision,"deny");});
test("canonical SSOT write is allowed",()=>{const result=run(["protect","--platform","codex","--kind","file"],payload({path:"project/.aidd/ssot/project.json"}));assert.equal(result.status,0);assert.equal(result.stdout,"");});
test("destructive shell command is denied",()=>{const result=run(["protect","--platform","codex","--kind","shell"],payload({command:"git reset --hard"},"PowerShell"));assert.equal(JSON.parse(result.stdout).hookSpecificOutput.permissionDecision,"deny");});
test("read-only shell command is allowed",()=>{const result=run(["protect","--platform","codex","--kind","shell"],payload({command:"git status --short"},"PowerShell"));assert.equal(result.status,0);assert.equal(result.stdout,"");});
test("UTF-8 conversation round trips and secrets are masked",()=>{const sandbox=mkdtempSync(join(tmpdir(),"aidd-log-test-"));try{const source=readFileSync(HOOK,"utf8");assert.match(source,/Buffer\.concat\(chunks\)\.toString\("utf8"\)/);const result=run(["local-log","--platform","codex","--role","user"],JSON.stringify({prompt:"한글 sk-12345678901234567890"}),{AIDD_LOCAL_CONVERSATION_LOG:"0"});assert.equal(result.status,0);assert.equal(result.stdout,"");}finally{rmSync(sandbox,{recursive:true,force:true});}});
test("provider configs contain no Python execution",()=>{for(const file of [".codex/hooks.json",".claude/settings.json"]){const text=readFileSync(join(ROOT,file),"utf8");assert.doesNotMatch(text,/(?:python(?:3)?|py\s+-3|\.py\b)/i);assert.match(text,/aidd(?:_hook)?\.mjs/);}});
test("Windows commands contain no shell variables",()=>{const config=JSON.parse(readFileSync(join(ROOT,".codex/hooks.json"),"utf8"));const commands=JSON.stringify(config.hooks);assert.doesNotMatch(commands,/\$repo|\$LASTEXITCODE|`\$/);assert.match(commands,/Join-Path \(git rev-parse --show-toplevel\)/);});
test("actual nested Windows command resolves Git root and preserves UTF-8",()=>{if(process.platform!=="win32")return;const config=JSON.parse(readFileSync(join(ROOT,".codex/hooks.json"),"utf8")),entry=config.hooks.PreToolUse.find(item=>JSON.stringify(item).includes("protect --platform codex --kind file")),command=entry?.hooks?.[0]?.commandWindows;assert.ok(command,"Codex file protection command is missing");const result=spawnSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",command],{cwd:join(ROOT,".ai"),input:payload({path:"project/docs/generated/한글.md"}),encoding:"utf8"});assert.equal(result.status,0,result.stderr);const output=JSON.parse(result.stdout);assert.equal(output.hookSpecificOutput.permissionDecision,"deny");assert.match(output.hookSpecificOutput.permissionDecisionReason,/한글\.md/);});
test("actual nested Windows SessionStart trust check reports a state",()=>{if(process.platform!=="win32")return;const config=JSON.parse(readFileSync(join(ROOT,".codex/hooks.json"),"utf8"));const command=config.hooks.SessionStart[0].hooks[0].commandWindows;const result=spawnSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",command],{cwd:join(ROOT,".ai"),encoding:"utf8"});assert.ok([0,1].includes(result.status),result.stderr);assert.match(result.stdout,/TRUST_RECORD_FOUND|REVIEW_REQUIRED/);});
